#!/bin/bash


cd $(dirname $0)
HOST="www.google.com"
O="Organization"
C="US"


openssl req -new -key master_server.key -out $HOST.csr \
-days 365 -subj '/C='$C'/O='$O'/CN='$HOST'' -config ca/openssl.ca.cnf

openssl ca -config ca/openssl.ca.cnf -notext  -out $HOST.crt  -infiles $HOST.csr 

rm $HOST.csr