#!/bin/bash

cd $(dirname $0)

openssl req -new -nodes -x509 -extensions v3_ca -keyout ca.key -out ca.crt -days 3600 \
-subj '/C=IL/ST=israel/L=jerusalem/O=NetFilter/OU=www.netfilter.com/CN=NetFilter Sign' -config openssl.ca.cnf

openssl genrsa -out ../master_server.key 1024

echo $(cd "$1"; pwd)"/"$(dirname $0)"/../../certs"